### ISSUE TITLE
Setting collectd::plugin::nginx params does not work for booleans

### ISSUE THREAD

**Issue by huasome** [voxpupuli/puppet-collectd#182]
Setting the nginx plugin parameters via hiera:

```
collectd::plugin::nginx:
  url:        "https://%{::fqdn}/nginx_status"
  verifypeer: 'false'
  verifyhost: 'false'
```

Doesn't work because the template

```
<% if @verifypeer -%>
  VerifyPeer <%= @verifypeer %>
<% end -%>
```

parses the value as a bool and never actually writes out the stanza. I'm not sure what the best way to fix this is except maybe use negative or an unless conditional?

**Comment by kitchen** [comment]
FWIW, the way I handle "tri-state bools" (true/false/undef) is like so:

```
define foo (
  $foo = undef
) {
  if (defined('$foo)) {
    $foo_bool = str2bool($foo)
  }
}
```

and then in template code:
```
<% if !@foo.nil? %>
  foo = <%= @foo ? 'true' : 'false' %>
<% end %>
```

this has the added benefit of normalizing boolean values on input to what the output should be. `str2bool` is from puppetlabs/stdlib, but that's ok since it's already used by this module :)

**Comment by kitchen** [comment]
I edited the last comment, sorry about that. I had typed up my old approach and realized that it was my old approach :)
