### ISSUE TITLE
StoreRates Parameter is missing in the amqp Plugin

### ISSUE THREAD

**Issue by michaelroth** [voxpupuli/puppet-collectd#215]
Die StoreRates Parameter is missing in the amqp Plugin.

**Comment by jyaworski** [comment]
Can you link some documentation?

**Comment by dhoppe** [comment]
@jyaworski I think he is referring to the [plugin options](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_amqp).

**Comment by bastelfreak** [comment]
@miroth70 
@dhoppe provided a fix which I just merged, could you check if everything is now working on your side?

**Comment by jyaworski** [comment]
Closing due to lack of response. Please re-open if needed.
