### ISSUE TITLE
Some errors in the code

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-collectd#235]
I use Geppetto and it shows all the errors that are present in the module.
I submitted a pull request with some easy fixes, but there are other present, which I am not sure what the intent was.
1. $ensure is absent
For example in curl_json.pp
```
  if $::osfamily == 'Redhat' {
    package { 'collectd-curl_json':
      ensure => $ensure,
    }
  }
```
Same issue in mysql.pp and ping.pp
2. In collectd::plugin::perl::plugin  $collectd::plugin::perl::filename doesn't exist
3. In postgresql.pp ,  concat call has ensure attribute, but it was added to concat module just recently, it doesn't exist in any released modules
4. in collectd::plugin::write_network
```
  class { 'collectd::plugin::network':
    server     => $servername,
    serverport => $serverport,
  }
```
neither server nor serverport attributes don't exist 

Cheers,
Vadym

**Comment by txaj** [comment]
Hi @vchepkov thanks for the report. 
1. Obviously the classes you're talking about are missing $ensure as a parameter. You can add it and default it as present
2. $base_filename does not seems used at all. just grep that string on the master branch, confirm it's not used anywhere then you can simply delete that line. 
3. I am unsure about this ; concat is a meta parameter, that should not be an issue. If you can find a case where it's an issue I could look deeper. PR'ing a test triggering that case would be great :-) 
4. this type is deprecated anyway. @blkperl how should we handle this ? PR for deprecated things you'd merge at the next major release ?

**Comment by blkperl** [comment]
Please submit a PR for the bugs you found. The deprecated things can be removed and I'll bump the version number to 5.0

**Comment by igalic** [comment]
1) looks fixed to me.

what's the status on the other bits? ping @vchepkov / @txaj

**Comment by jyaworski** [comment]
Closing due to lack of movement. Please re-open if needed.
