### ISSUE TITLE
Support for snmp v3

### ISSUE THREAD

**Issue by michaelrichardson** [voxpupuli/puppet-collectd#236]
It would be lovely to support snmp v3.  The source on github/collectd (commit 4ab54ded3b73d5051230bb35eecf766a51dee786) adds in this capability, though it hasn't filtered down through the main linux distribution packages yet.

I believe that basic patches to snmp.conf.erb and the related hosts/data templates would be enough, with the extra variables that v3 requires.  Something along the lines of

``` erb
 <% elsif val['Version'] = 3 %>
    Address "<%= val['Address'] %>"
    SecurityLevel "<%= val['SecurityLevel'] %>"
    Username "<%= val['Username'] %>"
    AuthProtocol "<%= val['AuthProtocol'] %>"
    AuthPassphrase "<%= val['AuthPassphrase'] %>"
    PrivacyProtocol "<%= val['PrivacyProtocol'] %>"
    PrivacyPassphrase "<%= val['PrivacyPassphase'] %>"
    Version <%= val['Version'] %>
    Collect <% val['Collect'].each do |x| -%>"<%= x -%>" <% end %>
    Interval <%= val['Interval'] %>
  <% end -%>
```

...for example.  Is anyone about to do this, or shall I submit a minor PR?

**Comment by txaj** [comment]
you can submit a PR

Please find out the exact collectd version required for that feature so you can properly write that if

**Comment by jyaworski** [comment]
@michaelrichardson are you still interested in a PR for this? There is support for minimum_version, so this could work.

**Comment by michaelrichardson** [comment]
Yes, I'll see if I can get one together.  Until recently, the official collectd packages also didn't support SNMPv3, so we were running with both a bleeding-edge patched collectd and my hodge-podge puppet modifications.  Thankfully, it's all mainline now, so will be much easier (particularly with the minimum_version above).

**Comment by jyaworski** [comment]
Awesome! Looking forward to it.

**Comment by jyaworski** [comment]
Ping @michaelrichardson again.
