### ISSUE TITLE
Cant set root_group

### ISSUE THREAD

**Issue by arenstar** [voxpupuli/puppet-collectd#263]
For security reasons i run collectd under the user collectd.

I cant define or override the params
https://github.com/pdxcat/puppet-module-collectd/blob/master/manifests/params.pp#L32

and cant define it from hiera either..

This would expect this to work
 
```
class { '::collectd':
        purge        => true,
        recurse      => true,
        purge_config => true,
        root_group   => 'collectd',
}
```

**Comment by arenstar** [comment]
```
class { '::collectd':
        purge        => true,
        recurse      => true,
        purge_config => true,
        root_user      => 'collectd',
        root_group    => 'collectd',
}
```
here is a PR that solves this :D 
https://github.com/pdxcat/puppet-module-collectd/pull/264

**Comment by txaj** [comment]
why a PR that modifies the user also ? wouldn't the ability to modify the group enough ? (mode modes are set to 640)

**Comment by jyaworski** [comment]
Closing due to lack of movement. Please re-open if needed.
