### ISSUE TITLE
Under Debian, does not update `collectd-core` when require => 'latest'

### ISSUE THREAD

**Issue by rymndhng** [voxpupuli/puppet-collectd#269]
If you're trying to perform an upgrade on an existing collectd installation and set `require => 'latest'`, `collectd-core` does not get updated.

I would argue that this is more of an issue on the Debian side not specifying version requirements for `collectd-core` but it'd be great if this module would abstract this problem away.

**Comment by txaj** [comment]
Could you give us a complete snippet to reproduce ? Aren't you looking to set latest here instead ?  https://github.com/pdxcat/puppet-module-collectd/blob/1830403421c03c10a00552075e164214e97c86da/manifests/init.pp#L16

**Comment by rymndhng** [comment]
On initial apply of puppet manifest, it works fine.

It doesn't work properly when performing an upgrade on an existing `collectd` installation:
1. run puppet with  `collectd` resource with parameter `require => 'latest'`.
(This will download the latest version of `collectd` and `collectd-core`)
2. new version of `collectd` is released
3. re-run puppet
(updates `collectd` but *not* `collectd-core`)

**Comment by txaj** [comment]
Well... 
```
# apt-cache show collectd|grep Depends
Depends: collectd-core, iptables, libc6 (>= 2.4), librrd4 (>= 1.3.0)
```

Is the mismatch between collectd and collectd-core causing issues ? If yes I'd also recommend to send this to Debian instead... Other than that I found unpractical to use ensure => latest anyway as it can cause surprise unplanned upgrades...

**Comment by rymndhng** [comment]
Yeah, I understand where you're coming from. In our setup we had `ensure => 'installed'`, but on decision to use this module to update to the latest version, it's behavior did not match the expectation. 

What I mean is that why have `ensure => 'latest'` if it's functionality is broken (albeit I haven't tried other platforms, hopefully they don't have this issue as well). I've filed a [ticket](https://bugs.launchpad.net/ubuntu/+source/collectd/+bug/1463916) upstream.

What are your thoughts on patching this inside the `collectd` module while this gets resolved though, because without managing the `collectd-core` package currently on Debian, `ensure => 'latest'` is broken.

**Comment by jyaworski** [comment]
I'd rather not have us code around OS packaging problems. However, we could ensure an array of packages on (I assume) <code>$::osfamily == 'Debian'</code>.

**Comment by jyaworski** [comment]
Let me know if #406 solves this for you.
