### ISSUE TITLE
plugin::chain: multiple attributes with the same key

### ISSUE THREAD

**Issue by matejzero** [voxpupuli/puppet-collectd#333]
Hello,
I have this case, where I'm using Chain plugin where I specify multiple arguments with the same key and different value. As far as I know, that is currently not possible with this module. Here is how the configuration looks like:

```puppet
class { 'collectd::plugin::chain':
  chainname => 'PreCache',
  rules     => [
    {
      'match'   => {
        'type'    => 'regex',
        'matches' => {
          'Plugin' => '.*',
        },
      },
      'targets' => [
        {
          'type'       => 'set',
          'attributes' => {
            'MetaDataSet' => "tsdb_tag_pluginInstance\" \"instance",
            'MetaDataSet' => "tsdb_tag_type\" \"type",
            'MetaDataSet' => "tsdb_tag_typeInstance\" \"type_instance",
            'MetaDataSet' => "tsdb_tag_dsname\" \"dsname",
          },
        },
      ],
    },
  ],
}
```

Could this be easily changed so I could use the same key names?
Also, how to specify multiple values like in my case. AFAIK its not possible at the moment.

This config is for the new write_opentsdb module (which is also used for pushing data to InfluxDB) that will come to collectd in the next release (hopefully). Pull request is already and waiting for merge.

**Comment by szop85** [comment]
Need this too :+1: :)

**Comment by Project0** [comment]
Have a look on the filter plugin, which abstract the full filter system with multiple chains/rules/matches/targets #322

**Comment by igalic** [comment]
@matejzero , @szop85 i'm not sure i understand what you *want* the config to look like.

**Comment by Project0** [comment]
@matejzero these are not valid options for the target "set", what you try to configure is not possible within the filter. The filter rules are not intended to configure a whole plugin.
I am not sure what you trie to do, but valid options for manipulating the instance/metric names are these:
Host String
Plugin String
PluginInstance String
TypeInstance String
see: https://collectd.org/documentation/manpages/collectd.conf.5.shtml#filter_configuration.

**Comment by jyaworski** [comment]
Closing due to lack of response. Please re-open if needed.
