### ISSUE TITLE
Plugin match_regex, target_set, write_tsdb missing

### ISSUE THREAD

**Issue by szop85** [voxpupuli/puppet-collectd#336]
Hey,

I'd like to request support for following collectd 5.5 plugins: match_regex, target_set and write_tsdb missing to enabled openTSDB support via puppet: https://github.com/collectd/collectd/pull/1107

Cheers,
Szop

**Comment by txaj** [comment]
I can see that write_tsdb is a released and documented (5.5) feature. 

However there's no documentation for match_regex and target_set, even in master : https://github.com/collectd/collectd/blob/master/src/collectd.conf.pod. Would you mind PRing such doc to collectd ?

**Comment by txaj** [comment]
After reading more carrefully the PR you linked, there is no collectd plugin named match_regex and/or target_set. So you're just requesting support for write_tsdb ?

**Comment by szop85** [comment]
Hey @txaj,

thank you for your fast response. It's [https://collectd.org/wiki/index.php/Match:RegEx], [https://collectd.org/wiki/index.php/Plugin:Write_TSDB] and [https://github.com/ymettier/collectd/commit/16c20a278d3b08f4f4288e30e14d8aea2f648710].

Cheers,
Szop

**Comment by szop85** [comment]
Hey @txaj ,

I guess I made a mistake since. Does the collectd puppet module actually include filters? As far as I can see "target_set" and "match_regex" are filters.

Cheers,
Szop

**Comment by Project0** [comment]
Have a look on #322, i have implemented the full filter stack with chain/match/set

**Comment by igalic** [comment]
does that mean we can now close this issue?

**Comment by jyaworski** [comment]
Closing this issue as it appears to be resolved. Please re-open if needed.
