### ISSUE TITLE
Doesn't seem to install disk plugin.

### ISSUE THREAD

**Issue by kwolf** [voxpupuli/puppet-collectd#366]
Looks like somewhere along the line this module stopped installing the disk plugin package on ::osfamily == RedHat.   I worked around it in our module because I'm lazy, but wanted to let you guys know.

This was with Collectd 5.5.x

**Comment by igalic** [comment]
@kwolf would you mind telling us *how* you worked around it?

**Comment by jyaworski** [comment]
Closing due to lack of response.

**Comment by danielbenzvi** [comment]
Same problem here.
Adding this to collectd::plugin::disk is an example of a lazy fix
```
  if $::osfamily == 'Redhat' {
    if $manage_package {
      package { 'collectd-ping':
        ensure => $ensure,
        onlyif => 'rpm -qa collectd|grep -q 5.5'
      }
    }
  }
``` 
and it will break if the version is above 5.5. but this should be fixed properly.
