### ISSUE TITLE
varnish plugin format - read-function of plugin `varnish/instance' failed

### ISSUE THREAD

**Issue by VAdamec** [voxpupuli/puppet-collectd#380]
Hi,
 I'm getting "read-function of plugin `varnish/instance' failed" with this simple puppet definition, it's collectd module error or am I doing something wrong ?

```
    class { 'collectd::plugin::varnish':
      instances => {
        'web' => {
          'CollectCache' => 'true',
          'CollectConnections' => 'true',
          'CollectBackend' => 'true',
          'CollectSHM' => 'true',
          'CollectESI' => 'false',
          'CollectFetch' => 'true',
          'CollectHCB' => 'false',
          'CollectSMS' => 'false',
          'CollectTotals' => 'true',
          'CollectWorkers' => 'true',
        }
      },
    }
```

Result on system:
<Plugin varnish>
  <Instance "web">
    CollectBackend true
    CollectCache true
    CollectConnections true
    CollectESI false
    CollectFetch true
    CollectHCB false
    CollectSHM true
    CollectSMS false
    CollectTotals true
    CollectWorkers true
  </Instance>
</Plugin>

[2015-12-16 09:19:29] read-function of plugin `varnish/web' failed. Will suspend it for 160.000 seconds.

If I remove instance name, it's ok:
<Plugin varnish>
  <Instance>
    CollectBackend true
    CollectCache true
    CollectConnections true
    CollectESI false
    CollectFetch true
    CollectHCB false
    CollectSHM true
    CollectSMS false
    CollectTotals true
    CollectWorkers true
  </Instance>
</Plugin>

[2015-12-16 09:19:29] varnish plugin: Unable to load statistics.
[2015-12-16 09:19:29] read-function of plugin `varnish/web' failed. Will suspend it for 160.000 seconds.
[2015-12-16 09:20:04] Exiting normally.
-- remove instance name and restart --
[2015-12-16 09:20:04] collectd: Stopping 5 read threads.
[2015-12-16 09:20:04] collectd: Stopping 5 write threads.
[2015-12-16 09:20:05] Initialization complete, entering read-loop.

**Comment by igalic** [comment]
i'm not entirely sure i understand this bug… :S

**Comment by jyaworski** [comment]
Can we have more information on this?

**Comment by juniorsysadmin** [comment]
@VAdamec Closing due to no response, feel free to re-open with more details so that someone can reproduce it
