### ISSUE TITLE
collectd::plugin::python::module does not support complex config

### ISSUE THREAD

**Issue by elemoine** [voxpupuli/puppet-collectd#390]
The `collectd::plugin::python::module` defined type doesn't currently support config hashes with hash or array values.

For example, the declaration

```puppet
collectd::plugin::python::module { 'foo':
  module => 'foo',
  script_source => "puppet:///modules/mymodule/foo.py",
  config => {
    "key0" => ["e0", "e1"],
    "key1" => {"k0" => "v0", "k1" => "v1"},
  },
}
```

currently produces this configuration fragment:

```
  Import "foo"
  <Module "foo">
    key0 ["e0, "e1"]
    key1 {"k0" => "v0", "k1" => "v1"}
  </Module>
```

which is incorrect, and will make collectd fail with a configuration parse error at startup time.

Instead the following should be produced:

```
  Import "foo"
  <Module "foo">
    key0 "e0"
    key1 "e1"
    key1 "k0" "v0"
    key1 "k1" "v1"
  </Module>
```

If you agree I can probably work on a pull request.

**Comment by igalic** [comment]
:+1:
