### ISSUE TITLE
New tag and add to forge

### ISSUE THREAD

**Issue by krjensen** [voxpupuli/puppet-collectd#401]
Hi,

Would you crate a new tag?

**Comment by jyaworski** [comment]
@igalic @nibalizer who creates tags for all of our modules?

**Comment by dhoppe** [comment]
@jyaworski Everybody of the Team "colleborators" should be able to do that, but it looks like the last release is from 2015-09-04. Somebody needs to take a look at the PR's and put them into the changelog.

**Comment by jyaworski** [comment]
Right, that's a github tag. Forge releases are different, or so I thought.

**Comment by dhoppe** [comment]
@jyaworski As you can see at [.travis.yml](https://github.com/voxpupuli/puppet-collectd/blob/master/.travis.yml#L33-L43) a Puppet Forge release is automatically triggered, if you create a tag and the build was successfull.

**Comment by rnelson0** [comment]
The process is documented at
https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module. Someone
will need to create a new PR first bumping the version, then the
`travis_release` rake target can be used from the updated 'master' branch.

**Comment by dhoppe** [comment]
@jyaworski This could be solved by bb27f97.
