### ISSUE TITLE
write_graphite plugin config not setting protocol on first run

### ISSUE THREAD

**Issue by johanek** [voxpupuli/puppet-collectd#421]
See: https://github.com/collectd/collectd/issues/866

In write_graphite config, the protocol value is correctly written if you have collectd 5.4 installed. If you're running a later version, then it's not set. See https://github.com/voxpupuli/puppet-collectd/blob/master/templates/plugin/write_graphite/carbon.conf.erb#L16

**Comment by jyaworski** [comment]
I don't follow. Protocol should be set if collectd >= 5.4. Is this not what you're seeing?

What configs are you using?

**Comment by johanek** [comment]
I think I read the code wrong. I noticed when downgrading to 5.4 the setting was only applied the second time the module was applied. This might have been my problem in the first place with 5.5.

I'll close this now and look at the behaviour again in the future, and re-open this if necessary.

**Comment by johanek** [comment]
Right, I've had a look at this again. What I'm seeing on a machine without collectd installed and with the ``minimum_version`` parameter set to 5.5, on the first puppet run I get a write_graphite config file that looks like this:

```
<Plugin write_graphite>
<Carbon>
  Host "graphiterelay1.sohonet.internal"
  Port "2003"
  Prefix "dsn.sohonet."
  EscapeCharacter "_"
  StoreRates false
  AlwaysAppendDS false
  SeparateInstances true
</Carbon>
</Plugin>
```

On the second run, I get this diff:

```
--- /etc/collectd/conf.d/05-logfile.conf        2016-04-18 09:39:21.232903000 +0000
+++ /tmp/puppet-file20160418-38065-1hcxspc      2016-04-18 09:45:02.852903000 +0000
@@ -1,9 +1,12 @@
 # Generated by Puppet
-LoadPlugin logfile
+<LoadPlugin logfile>
+  Globals false
+</LoadPlugin>
 <Plugin logfile>
   LogLevel info
   File "/var/log/collectd.log"
   Timestamp true
+  PrintSeverity false
 </Plugin>
 <Plugin logfile>
   LogLevel info
   File "/var/log/collectd.log"
   Timestamp true
+  PrintSeverity false
 </Plugin>
 
 
--- /etc/collectd/conf.d/write_graphite-config.conf     2016-04-18 09:39:21.296903000 +0000
+++ /tmp/puppet-file20160418-38065-1oikgic      2016-04-18 09:45:02.916903000 +0000
@@ -1,5 +1,5 @@
 <Plugin write_graphite>
-<Carbon>
+<Node "graphiterelay">
   Host "graphiterelay1.sohonet.internal"
   Port "2003"
   Prefix "dsn.sohonet."
@@ -7,5 +7,7 @@
   StoreRates false
   AlwaysAppendDS false
   SeparateInstances true
-</Carbon>
+  LogSendErrors true
+  Protocol "tcp"
+</Node>
 </Plugin>
```

So it appears that the ``collectd_version_real`` variable set in #412 is not working correctly.

It looks to me that the ``collectd_version`` fact returns nil when collectd isn't installed. ```pick``` as used at https://github.com/voxpupuli/puppet-collectd/blob/master/manifests/init.pp#L34 will return the first value that is not undefined or an empty string. So in this case, it returns nil.

I'm about to raise a PR which sets the ``collectd_version`` fact to an empty string if collectd isn't installed, which corrects this behaviour.

It's a bit of a pain to write spec tests for this in the ``collectd::plugin::write::graphite::carbon`` define - you can set the collectd_version fact, but the minimum_version parameter is set at the main class and I can't see how to set that.
