### ISSUE TITLE
python plugin requires config section for modules

### ISSUE THREAD

**Issue by eriweb** [voxpupuli/puppet-collectd#424]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Must pass config to Collectd::Plugin::Python::Module[postfix] on node localhost

The particular module does not require any configuration and is simply a blank <Module 'postfix></Module>

**Comment by jyaworski** [comment]
We can set it to an empty hash.

**Comment by eriweb** [comment]
That would be great, currently I work around it by having a dummy hash, but would be great to get rid of that
