### ISSUE TITLE
The python plugin appears to be broken

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/puppet-collectd#428]
I have the following collectd config for my python plugin, generated via puppet (minus the syslog line):

```shell
[root@jump1 ~]# cat /etc/collectd.d/python-config.conf 
# Generated by Puppet
LoadPlugin "syslog"
<Plugin "python">
  ModulePath "/usr/share/collectd/python"
  LogTraces false
  Interactive false
  Import "puppet_reports"

  <Module "puppet_reports">
    ReportsDir "/var/lib/puppet/reports"
  </Module>
</Plugin>
```
This generates the following logs:

```syslog
Mar 17 15:08:21 jump1 collectd[4464]: There is a `Module' block within the configuration for the python plugin. The plugin either only expects "simple" configuration statements or wasn't loaded using `LoadPlugin'. Please check your configuration.
Mar 17 15:08:21 jump1 collectd[4470]: plugin_load: Could not find plugin "python" in /usr/lib64/collectd
Mar 17 15:08:21 jump1 collectd[4470]: Found a configuration for the `python' plugin, but the plugin isn't loaded or didn't register a configuration callback.
```

I'm using collectd 5.4.0.

If it matters, the plugin in question is https://collectd.org/wiki/index.php/Plugin:puppet_reports

**Comment by dhoppe** [comment]
@jyaworski How does your manifest look like? According to the wiki the wrong module is loaded (syslog instead of python).

**Comment by jyaworski** [comment]
@dhoppe I used this:

http://stackoverflow.com/questions/22402445/collectd-plugin-seems-to-not-start

It's all hiera-based, so I have the following:

```yaml
collectd::plugin::python::modules:
  'puppet_reports':
    config:
      ReportsDir: '"/var/lib/puppet/reports"' # Yes, this is really needed
    script_source: 'puppet:///modules/profiles/collectd/python/puppet_reports.py'
```

**Comment by dhoppe** [comment]
@jyaworski I did some tests via Vagrant and the module is working as expected. I just had to install the package ```python-yaml```, because this is a dependency of the ```puppet_reports``` check. 

The Python plugin is loaded via ```10-python.conf```. Are you sure your error message is related to the ```puppet_reports``` check?

**Comment by jyaworski** [comment]
I also see this in the logs:

```syslog
Mar 17 17:30:42 jump1 collectd[13130]: plugin_load: Could not find plugin "python" in /usr/lib64/collectd
```

On a whim, I looked to see if collectd-python was installed. It was not.

We should ensure the package's existence.

Now it looks like it isn't actually sending any data, but that's the actual script's fault and not the collectd plugin.
