### ISSUE TITLE
Plugins should have a default of collectd::package_ensure, not their own

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/puppet-collectd#430]
If I set collectd::package_ensure to latest, it should set the default for all of the plugins as well.

**Comment by igalic** [comment]
sounds like a major change of current behaviour… and a lot of refactoring work.

**Comment by dhoppe** [comment]
I do not think so. This is just an sed command which changes present to latest. It makes sense to do this kind of updates automatically.

**Comment by igalic** [comment]
:+1: :exclamation:  do it so, :hash: :one: :bangbang:

**Comment by markasammut** [comment]
I have submitted a PR which fixes this for a set of plugins I use:
https://github.com/voxpupuli/puppet-collectd/pull/1010

Same should be done for all other plugins
