### ISSUE TITLE
Plugin `df' did not register for value `ReportReserved'.

### ISSUE THREAD

**Issue by xaniasd** [voxpupuli/puppet-collectd#435]
According to the documentation, there is no parameter ReportReserved defined for the df plugin
https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_df

The corresponding template does however add it, and as a result I get an error log as seen in the title of this issue. This is at least the case for collectd 5.5

It should be possible to make this value optional (e.g. by assigning a default **undef** value to it)

**Comment by jyaworski** [comment]
@xaniasd are you aware if this existed in previous versions, and what version it stopped existing? We could cue off <code>collectd_version</code> if so.

**Comment by xaniasd** [comment]
@jyaworski according to this: https://collectd.org/wiki/index.php/Plugin:DF, it existed since 4.9. I don't know when it disappeared, I believe it was still there at 5.1 (shouldn't be difficult to check anyway).

**Comment by jyaworski** [comment]
It looks like it was removed in 5.5.
