### ISSUE TITLE
Support the MD plugin

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/puppet-collectd#464]
https://collectd.org/wiki/index.php/Plugin:MD

**Comment by bzed** [comment]
works perfectly fine with `::collectd::plugin{ 'md' : }` - what else do you need?

**Comment by jyaworski** [comment]
@bzed I'm just going to silently close this ticket and pretend I never opened it. :)

Maybe I should have looked further into what plugins were in the base package.

**Comment by bzed** [comment]
Well, the question for me is if every little collectd plugin, which does not need a config at all, should have a puppet class. It would make it easier to use the plugin from foreman or others, but at the same time its a waste of code. Not sure what the best thing to do is.
