### ISSUE TITLE
collectd-disk does not exist

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-collectd#514]
Hi,

on RHEL/CentOS 7, the package collect-disk does not exist. puppet will run into an error, if the collect disk plugin is enabled.

**Comment by jkroepke** [comment]
See comments on #466

**Comment by jkroepke** [comment]
> # puppet agent -t 
> Notice: Ignoring --listen on onetime run
> Info: Retrieving pluginfacts
> Info: Retrieving plugin
> Info: Loading facts
> Info: Caching catalog for host
> Info: Applying configuration version '1464361625'
> Error: Execution of '/usr/bin/yum -d 0 -e 0 -y --enablerepo=epel7 install collectd-disk' returned 1: Error: Nothing to do
> Error: /Stage[main]/Collectd::Plugin::Disk/Package[collectd-disk]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y --enablerepo=epel7 install collectd-disk' returned 1: Error: Nothing to do
> Notice: /Stage[main]/Collectd::Plugin::Disk/Collectd::Plugin[disk]/File[disk.load]/ensure: created
> Info: /Stage[main]/Collectd::Plugin::Disk/Collectd::Plugin[disk]/File[disk.load]: Scheduling refresh of Service[collectd]
> Notice: /Stage[main]/Collectd::Service/Service[collectd]: Triggered 'refresh' from 1 events
> Notice: Finished catalog run in 17.64 seconds

**Comment by jkroepke** [comment]
The collectd package will install disk.so plugin

```
yum provides /usr/lib64/collectd/disk.so
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
collectd-5.5.1-2.el7.x86_64 : Statistics collection daemon for filling RRD files
Repo        : @epel7
Matched from:
Filename    : /usr/lib64/collectd/disk.so
```

**Comment by jyaworski** [comment]
On the official collectd repo, a collectd-disk package exists.

http://pkg.ci.collectd.org/rpm/collectd-5.5/epel-7-x86_64/

If you use a different repo, use hiera to set collectd::plugin::manage_package: false

**Comment by jkroepke** [comment]
An option like collectd::use_upstream_packages would be better. Most of the RHEL users won't be used 3th party repositories.

For the manage_package workaround, see #513

**Comment by jyaworski** [comment]
This module supports more than RHEL. Is there a reason that collectd::plugin::disk::manage_package can't be set to false? That's what I'm using in my environment where I don't have the upstream repo.

**Comment by jkroepke** [comment]
In my opinion, a puppet module should work on out of the box without pre configure some repositories.

If your module requires since the last update the upstream collectd repo, you should manage the yum repo/apt source, too. (For example see jfryman/nginx module, puppetlabs/postresql). This behavior should be also configurable and if it set to false puppet should not install unknown packages.

Joseph (Jy) Yaworski <notifications@github.com<mailto:notifications@github.com>> schrieb am Di., 31. Mai 2016, 18:53:

This module supports more than RHEL. Is there a reason that collectd::plugin::disk::manage_package can't be set to false? That's what I'm using in my environment where I don't have the upstream repo.

**Comment by jyaworski** [comment]
It doesn't require the upstream repo necessarily. However, you make a good point. What do you think about adding a manage_repo param, defaulting to true, and pointing it to http://pkg.ci.collectd.org/rpm/master/epel-7-x86_64/ (adjusting for rpm/deb, os version, etc)?

**Comment by jkroepke** [comment]
This would be great.

I prefer different classes for deb / apt like `collectd::repo::debian` and `collectd::repo::redhat`. The repo url should be also a parameter. This is useful for users with local mirrors.

**Comment by senax** [comment]
setting manage_package to false doesn't seem to work for me on RHEL7 with Puppet4; it still sets _manage_package to true.

`  if $manage_package {`
should be
`    if $manage_package != undef {`

**Comment by senax** [comment]
Aahhh, sorry my bad. It is already fixed in master but not released to the puppet forge yet. Would be nice if we could have the fixed version? We can't clone from github here at work but are allowed to download from the forge.
