### ISSUE TITLE
RabbitMQ: Fails with pip not installed

### ISSUE THREAD

**Issue by Yuav** [voxpupuli/puppet-collectd#575]
```
Error: Could not set 'present' on ensure: Could not locate command pip and pip-python. at 66:/etc/puppetlabs/code/environments/production/modules/collectd/manifests/plugin/rabbitmq.pp
Error: Could not set 'present' on ensure: Could not locate command pip and pip-python. at 66:/etc/puppetlabs/code/environments/production/modules/collectd/manifests/plugin/rabbitmq.pp
Wrapped exception:
Could not locate command pip and pip-python.
Error: /Stage[main]/Collectd::Plugin::Rabbitmq/Package[collectd-rabbitmq]/ensure: change from absent to present failed: Could not set 'present' on ensure: Could not locate command pip and pip-python. at 66:/etc/puppetlabs/code/environments/production/modules/collectd/manifests/plugin/rabbitmq.pp
```

**Comment by Yuav** [comment]
Manually installing pip makes the Puppet run succeed, but this error is then logged by collectd

```
[2016-10-21 12:08:41] python plugin: Error importing module "collectd_rabbitmq.collectd_plugin".
[2016-10-21 12:08:41] Unhandled python exception in importing module: ImportError: No module named collectd_rabbitmq.collectd_plugin
[2016-10-21 12:08:41] python plugin: Found a configuration for the "collectd_rabbitmq.collectd_plugin" plugin, but the plugin isn't loaded or didn't register a configuration callback.

```

**Comment by jyaworski** [comment]
@bilsch might have some input here.

**Comment by xaque208** [comment]
Maybe xaque208/puppet-python can help.

**Comment by bilsch** [comment]
@Yuav 

@jyaworski is correct we use another puppet module to manage getting python and pip installed. We use https://github.com/stankevich/puppet-python - would be nice to know if the one @xaque208 mentioned works ( guessing it does since they are the one who commented on it ;) )

In our profile we have something along the lines of:

```
class { '::collectd::plugin::rabbitmq':
  config => {
    ... blah,
  },
  manage_package => true,
  package_provider => 'pip',
}
```

Hope that helps!

**Comment by jyaworski** [comment]
@bastelfreak what do you think about adding https://github.com/stankevich/puppet-python as a dependency? It's already a dependency for puppet-puppetboard.

**Comment by Yuav** [comment]
I'd say if it can be avoided, it should be avoided. I think the stackevich approach to pip is broken by design, but that's a different story. Pip is a bit tricky, as it's not available as a package in all distros by default, but I'd suggest something along the lines of https://github.com/Yuav/puppet-pip/blob/master/manifests/install.pp

**Comment by bastelfreak** [comment]
IMO managing pip is out of scope for this module and should be handled in a profile. We should add a note to our README.md that this plugin requires pip. A working example in the examples/ directory would also be great. There are several modules available to manage pip, so making a dependency to one of them will break the plugin for users of all other pip modules.

**Comment by Yuav** [comment]
I'd say you can use an ifdef and install pip from repo, but not depend on module. Creating code that doesn't work with default settings is bad practice IMO.

**Comment by dhoppe** [comment]
@voxpupuli/project-maintainers  Similar to `manage_repo` and `manage_package` we could add the support for `manage_python`, but this should be handled at `install.pp` and not for a specific plugin, right?

**Comment by jyaworski** [comment]
Absolutely @dhoppe. A++.
