### ISSUE TITLE
Migrate to official apt repos

### ISSUE THREAD

**Issue by Yuav** [voxpupuli/puppet-collectd#578]
Currently implemented

    http://ppa.launchpad.net/collectd/collectd-5.5/ubuntu

Should be updated to 

    deb http://pkg.ci.collectd.org/deb/ <codename> <branch>

As described in: https://github.com/collectd/collectd-ci/blob/master/README.md

**Comment by dhoppe** [comment]
@voxpupuli/project-maintainers It would be nice to have support for Collectd 5.6, but do we want to depend on CI packages? It is kind of bleeding edge to get a new package after every successful build.

**Comment by petems** [comment]
I think a parameter called "edge repo" or "bleeding repo" or whatever would be good. 

I already have some code like this in one of my profiles:

```puppet
yumrepo { 'collectd':
    ensure  => present,
    enabled => '1',
    baseurl => "https://pkg.ci.collectd.org/rpm/collectd-${collectd_version}/epel-${::os['release']['major']}-${::os['architecture']}",
    gpgkey  => 'https://pkg.ci.collectd.org/pubkey.asc',
    before  => Class['::collectd'],
  }
```

So we could do this for RHEL-ish and APT-ish systems 👍
