### ISSUE TITLE
Manipulating yaml data when formatting for use in collectd::plugin::snmp

### ISSUE THREAD

**Issue by robotman321** [voxpupuli/puppet-collectd#580]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.2 w/ future parser turned on
- Ruby: 1.8.7
- Distribution: CentOS 6.8
- Module version: Any

### What are you seeing
The issue is that when using the snmp plugin, the data and hosts options per item, their keys are Camel Cased. We use this module with a correlating yaml file that contains the same structure the module is expecting.

Our issue is that as of 3.8 with the future parser (and then in puppet 4) submitting Variable names with a capital letter are deprecated (which is how we manipulate this data later in the manifest that calls the collectd module). I understand a LOT of people use this module, but would it be a worthwhile en devour to change something like:

`class {'collectd::plugin::snmp':
  data  =>  {
    amavis_incoming_messages => {
      'Type'        => 'counter',
      'Table'       => false,
      'Instance'    => 'amavis.inMsgs',
      'Values'      => ['AMAVIS-MIB::inMsgs.0'],
      'Ignore'      => [ '00:00', '*IgnoreString' ],
      'InvertMatch' => false,
    }
  },`
to be
`class {'collectd::plugin::snmp':
  data  =>  {
    amavis_incoming_messages => {
      'type'        => 'counter',
      'table'       => false,
      'instance'    => 'amavis.inMsgs',
      'values'      => ['AMAVIS-MIB::inMsgs.0'],
      'ignore'      => [ '00:00', '*IgnoreString' ],
      'invertMatch' => false,
    }
  },`
(as well changing the corresponding ERB file that generates the config files to handle the lowercase keys.

If there is a specific reason it was done like this, i'll understand I just wanted to get some feedback from the experts as to why this was setup like this.

Thank you in advance!

**Comment by jyaworski** [comment]
That would be a breaking change, but it should have been snake_case anyway. Would you file a PR?

**Comment by robotman321** [comment]
Sure thing @jyaworski ill have something up this week.

**Comment by juniorsysadmin** [comment]
@robotman321 ping

**Comment by robotman321** [comment]
Sorry.. been swamped at work, ill work on this today.

**Comment by robotman321** [comment]
I see there are a few more instances that need updating to bring all variable names into the same scope of snake_case. Thoughts on opening a new PR with all the fixes? (sorry my OCD kicked in seeing them..)

**Comment by juniorsysadmin** [comment]
> Thoughts on opening a new PR with all the fixes?
Do this one first, then perhaps one for all the others
