### ISSUE TITLE
collectd::plugin::python::module does not support multiple configs for the same module

### ISSUE THREAD

**Issue by kazeborja** [voxpupuli/puppet-collectd#581]
Hi, I'm in the need to achieve something like this, where I can have the same Python module with different configurations, even when then, the actual implementation of the module is a bit tricky.

```
<Plugin "python">
  ...
  Import "collectd-sensor"

  <Module "collectd-sensor">
    module_name "lemon-sensor-facts"
    metric_id 13173
    metricclass "facts.facts"
  </Module>

  <Module "collectd-sensor">
    module_name "sensor_flume"
    metric_id 13045
    metricclass "flume_agent.flumefch"
  </Module>
</Plugin>
```

Is there any reason for the Python plug-in not to allow it? I've coded some modifications within the code to be able to do it, that I'd love to submit as a PR if you think that makes sense and no one else is working on it.

**Comment by bastelfreak** [comment]
Hi @kazeborja, thanks for rising the issue. I'm not 100% familiar with the plugin, can you provide the patch so we can review (and maybe merge) it?

**Comment by kazeborja** [comment]
Hi @bastelfreak 

I've submitted a MR with the changes so you can take a look to it, let me know if there is something wrong/weird with it.
