### ISSUE TITLE
Array sorted in python module

### ISSUE THREAD

**Issue by GillesBIANNIC** [voxpupuli/puppet-collectd#586]
Hello,

In the python module, there is a template used to write config files for collectd.

https://github.com/voxpupuli/puppet-collectd/blob/master/templates/plugin/python/module.conf.erb#L7

Values are written in an order (with a sort). I understand : this is puppet's logic.
But, I think it shouldn't be like this for arrays (see line 7). We're loosing the array's order to an alphabetic order :/
This is a problem because the array in puppet's config is not the same in the file (order has been changed).
For my part, I removed the sort and replaced this code :

  <%- if value.is_a?(Array) -%>
  <%- value.sort.each do |v| -%>
    ...
  <%- end -%>

By this :

  <%- if value.is_a?(Array) -%>
  <%- value.each do |v| -%>           # no sort
    ...
  <%- end -%>

in this file : https://github.com/voxpupuli/puppet-collectd/blob/master/templates/plugin/python/module.conf.erb#L7

Thanks for your attention,

Gilles

**Comment by petems** [comment]
@GillesBIANNIC Is there a requirement to have the values in a specific order? Does it change the behaviour if it is ordered differently?

**Comment by GillesBIANNIC** [comment]
Everywhere arrays are ordered, so I was very surprised when I discovered the alphabetic order.
We're using a plugin which reads some RegExs in a config file and apply them one by one (in the config order) on strings. If Puppet changes the order of the regexs in config, the result will not be the same :(

**Comment by traylenator** [comment]
The templates contain no sort anymore so this is presumably fixed.
