### ISSUE TITLE
Failed to parse template collectd/loadplugin.conf.erb: undefined method `scan' for 5.4:Float

### ISSUE THREAD

**Issue by kwisatz** [voxpupuli/puppet-collectd#587]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 2.1.1
- Distribution: Debian 8.6
- Module version: 5.1.0

### How to reproduce (e.g Puppet code you use)

Unable to tell which class is causing this as the logs do not specify.

### What are you seeing

Run fails with output pasted below

### What behavior did you expect instead

Run succeeds

### Output log

```
Nov 26 17:17:55 puppet puppet-master[17263]: Failed to parse template collectd/loadplugin.conf.erb:
Nov 26 17:17:55 puppet puppet-master[17263]:   Filepath: /usr/lib/ruby/vendor_ruby/puppet/util/package.rb
Nov 26 17:17:55 puppet puppet-master[17263]:   Line: 4
Nov 26 17:17:55 puppet puppet-master[17263]:   Detail: undefined method `scan' for 5.4:Float
Nov 26 17:17:55 puppet puppet-master[17263]:  at /etc/puppet/environments/cl1_prod/modules/collectd/manifests/plugin.pp:22 on node node1
[…]
Nov 26 17:10:57 puppet puppet-master[17263]: Failed to parse template collectd/loadplugin.conf.erb:
Nov 26 17:10:57 puppet puppet-master[17263]:   Filepath: /usr/lib/ruby/vendor_ruby/puppet/util/package.rb
Nov 26 17:10:57 puppet puppet-master[17263]:   Line: 4
Nov 26 17:10:57 puppet puppet-master[17263]:   Detail: undefined method `scan' for 5.4:Float
Nov 26 17:10:57 puppet puppet-master[17263]:  at /etc/puppet/environments/cl1_prod/modules/collectd/manifests/plugin.pp:22 on node node2
```

### Any additional information you'd like to impart

Looks like it's trying to run a method on a float which is only available on strings.

I have the following config for the collectd class:

```yaml
collectd::purge: true
collectd::recurse: true
collectd::purge_config: true
collectd::minimum_version: '5.4'
```

**Comment by kwisatz** [comment]
I'm also seeing this prior to some of the errors above, which might be related (not though that this is not always the case, i.e. not on all of the nodes that produce this error)

```
(Scope(Class[Collectd::Plugin::Apache])) Could not look up qualified variable 'collectd::package_install_options'; class collectd has not been evaluated
```

**Comment by juniorsysadmin** [comment]
@kwisatz Can you confirm that you're still getting the problem with latest git master + Ruby 2.1.latest?

**Comment by kwisatz** [comment]
@juniorsysadmin Are you referring to the class evaluation or the Float.scan issue?
To be quite honest, the Float.scan issue, I haven't seen it in a while, but I don't remember what I changed to make it go away :(

**Comment by juniorsysadmin** [comment]
Closing for now
