### ISSUE TITLE
Template in collectd::plugin::perl::plugin generates unstable output

### ISSUE THREAD

**Issue by blajos** [voxpupuli/puppet-collectd#635]
Hi,

We are using collectd::plugin::perl::plugin to collect data from some rabbitmq servers. But the generated config file is changing regurarly.

The simplest solution would be to use sort on hashes in file templates/plugin/perl/plugin.erb.

Thanks,
Lajos

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 1.8.7
- Distribution: CentOS 6/7
- Module version: 4.2.0

## How to reproduce (e.g Puppet code you use)
```puppet
  collectd::plugin::perl::plugin { 'RabbitMQ':
    module      => 'RabbitMQ',
    include_dir => '/usr/local/collectd',
    provider    => 'file',
    source      => 'puppet:///files/usr/local/collectd/RabbitMQ.pm',
    destination => '/usr/local/collectd',
    config      => {
      'Username' => 'collectd',
      'Password' => 'very_secure',
      'Port'     => 15672,
      'Host'     => 'localhost',
      'Realm'    => 'RabbitMQ Management',
    },
    require     => File['/usr/local/collectd'],
  }
```

## What are you seeing
Config lines move around regurarly on puppet runs.

## What behaviour did you expect instead
Config lines should stay put.

## Any additional information you'd like to impart
Used versions are pretty old, but the current code still has the same issue.

**Comment by oranenj** [comment]
I'll assume this is fixed and close this issue, because the PR is merged
