### ISSUE TITLE
Process plugin silently breaks processmatch/process defines.

### ISSUE THREAD

**Issue by bzed** [voxpupuli/puppet-collectd#652]
@devfaz with 395036ae332c56800481459fef9f1691a484de9f you've **silently** broken the usage of collectd::plugin::processes::processmatch and collectd::plugin::processes::process as the concat fragments from both defines are not collected anymore unless you've specified a process or processmatch option in the collectd::plugin::processes class.

The correct fix would be to use collectd from wheezy-backports or maybe make collectd monitor itself by default.

**Comment by juniorsysadmin** [comment]
Fixed by #712
