### ISSUE TITLE
collectd::plugin::python::module does not support number options

### ISSUE THREAD

**Issue by LionelCons** [voxpupuli/puppet-collectd#662]
This module (via module.conf.erb) only supports boolean and string options.

When a number is given (e.g. config => [{ 'Port' => 1234}]), Puppet fails with "undefined method scan for 1234:Fixnum".

When a string is given (e.g. config => [{ 'Port' => '1234'}]), we end up with a string in python-config.conf.

Please add support for numbers: they should be rendered as they are, with no double quotes around.

**Comment by juniorsysadmin** [comment]
@traylenator Label fixed
