### ISSUE TITLE
Why does the python plugin insist on permissions? 

### ISSUE THREAD

**Issue by standaloneSA** [voxpupuli/puppet-collectd#679]
The python plugin cost me several hours of downtime on a very critical machine today. 

Essentially, my WSGI web-apps were unable to be loaded by the www-data user because imports failed if the code lived in /usr/local/lib/python2.7/dist-packages 

[Tue Jun 06 06:48:36.043677 2017] [wsgi:error] [pid 5903:tid 140137233069824] [client #IP#:50420] File "/var/svn/trac/main/htdocs/trac.wsgi", line 30, in application
[Tue Jun 06 06:48:36.043722 2017] [wsgi:error] [pid 5903:tid 140137233069824] [client #IP#:50420] from trac.web.main import dispatch_request
[Tue Jun 06 06:48:36.043747 2017] [wsgi:error] [pid 5903:tid 140137233069824] [client #IP#:50420] ImportError: No module named trac.web.main

The reason was tracked back to this module which, as described by the readme: 

 * `modulepaths` is an array of paths where will be Collectd looking for Python modules, Puppet will ensure that each of specified directories exists and it is owned by `root` (and `chmod 0750`). If you don't specify any `modulepaths` a default value for given distribution will be used.

What is the reason for setting module paths to 750?

**Comment by alexjfisher** [comment]
@standaloneSA Sorry to hear you've had a bad experience.  It appears this issue is fixed in the latest release.
https://github.com/voxpupuli/puppet-collectd/blob/v5.3.0/manifests/plugin/python.pp#L63
