### ISSUE TITLE
Time for a new version ?

### ISSUE THREAD

**Issue by tpoindessous** [voxpupuli/puppet-collectd#684]
Hi

last version is 5 month old and since this version, you fixed some bugs and added some features.

We would love to have a new version in puppetforge.

Do you need any help that would be useful ?

Thanks for your work.

Thomas.

**Comment by bastelfreak** [comment]
Hi @tpoindessous, thanks for rising this issue. I would like to kick a new release, but https://github.com/voxpupuli/puppet-collectd/pull/673 is currently a blocker and I'm unsure about the best way to fix it.

**Comment by nicobrevin** [comment]
looks fixed now, new version please?

**Comment by traylenator** [comment]
Many releases made since 2017
