### ISSUE TITLE
plugin::mysql::database - remove default 'UNSET' values

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/puppet-collectd#724]
Use better types to make it clearer that these parameter are required

**Comment by ph448** [comment]
@juniorsysadmin what would you consider a 'better type' for the username? IMO the best course of action is to not provide a default and make the manifest fail early and hard with the familiar message saying a String was expected.
scratching a personal itch I have a PR cooking that makes supplying the password optional and sets the default hostname to 'localhost', as this better matches the expectations a MySQL user might have, and it would be nice to complete a fix for this issue.

**Comment by juniorsysadmin** [comment]
> IMO the best course of action is to not provide a default and make the manifest fail early and hard with the familiar message saying a String was expected.

@ph448 Sounds reasonable. I have not touched Puppet for years though.
