### ISSUE TITLE
Cannot specify ci_package_repo => 5.8 even though 5.8 is available

### ISSUE THREAD

**Issue by steveames** [voxpupuli/puppet-collectd#741]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## What are you seeing
Cannot specify ci_package_repo => '5.8'.

## What behaviour did you expect instead
5.8 was released recently. Kind of expected to be able to say 5.8 :)

**Comment by bastelfreak** [comment]
Hi @steveames, thanks for the report. Which exact error message do you get?

**Comment by steveames** [comment]
5.8 doesn't match the pattern. in manifests/init.pp there is a pattern:

  Optional[Pattern[/(^5.4|^5.5|^5.6|^5.7|^master)/]] $ci_package_repo = $collectd::params::ci_package_repo,

When I tried to use 5.8 it gave me an error pointing to that. I added 5.8 on my local branch and am back in business.

**Comment by steveames** [comment]
https://pkg.ci.collectd.org/deb/dists/xenial/

**Comment by alexjfisher** [comment]
This was fixed a while back in https://github.com/voxpupuli/puppet-collectd/pull/752
