### ISSUE TITLE
processes-config.conf file is not created

### ISSUE THREAD

**Issue by traylenator** [voxpupuli/puppet-collectd#926]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.14.0
- Ruby: 
- Distribution: CentoS 7
- Module version: 11.3.1-rc0
- Collectd version 5.8.1

## How to reproduce (e.g Puppet code you use)

```puppet
collectd::plugin::processes::processmatch{'eosd':
      collect_file_descriptor => true,
      collect_memory_maps     => true,
      collect_context_switch  => false,
      regex => 'eosd .*$',
    }
```
Apply manifest.

## What are you seeing

The file `/etc/collectd.d/processes-config.conf` is not created.

## What behaviour did you expect instead
The file should  I think be created with, certainly the metrics are not enabled.

```apache
<Plugin processes>
      <ProcessMatch "eosd" "eosd .*$">
        CollectContextSwitch false
        CollectFileDescriptor true
        CollectMemoryMaps true
      </ProcessMatch>
    </Plugin>
```
## Output log

Running `puppet agent -d | grep Proces` on above manifest.

```
 puppet apply /test.pp  -d  --color false | grep lugin::Proc    
Debug: Scope(Class[Collectd::Plugin::Processes]): Retrieving epp template collectd/plugin/processes-header.conf.epp
Debug: Scope(Collectd::Plugin::Processes::Processmatch[eosd]): Retrieving epp template collectd/plugin/processes/processmatch.conf.epp
Debug: /Stage[main]/Collectd::Plugin::Processes/Concat[/etc/collectd.d/processes-config.conf]/notify: notify to Service[collectd]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[processes.load]/notify: notify to Service[collectd]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[older_processes.load]/notify: notify to Service[collectd]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[old_processes.load]/notify: notify to Service[collectd]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[package_processes.load]/notify: notify to Service[collectd]
Debug: /Stage[main]/Collectd::Plugin::Processes/Concat[/etc/collectd.d/processes-config.conf]/Concat_file[/etc/collectd.d/processes-config.conf]/before: before to File[package_processes.load]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[processes.load]: Adding autorequire relationship with File[collectd.d]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[older_processes.load]: Adding autorequire relationship with File[collectd.d]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[old_processes.load]: Adding autorequire relationship with File[collectd.d]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[package_processes.load]: Adding autorequire relationship with File[collectd.d]
Debug: /Stage[main]/Collectd::Plugin::Processes/Concat[/etc/collectd.d/processes-config.conf]/Concat_file[/etc/collectd.d/processes-config.conf]: Skipping automatic relationship with File[package_processes.load]
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[older_processes.load]: Nothing to manage: no ensure and the resource doesn't exist
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[old_processes.load]: Nothing to manage: no ensure and the resource doesn't exist
Debug: /Stage[main]/Collectd::Plugin::Processes/Collectd::Plugin[processes]/File[package_processes.load]: Nothing to manage: no ensure and the resource doesn't exist

```
## Any additional information you'd like to impart
Running a git bisect the behaviour changed with

a864d0d58815d58c944277417dcf52df2d3c7572

**Comment by traylenator** [comment]
Hi @paramite 

Just deciding how best to fix this, maybe you have some comment?

* I see either just change the configuration name that puppet creates away from `processes-config.conf`
* Migrate to 10-proceses.conf to be a concat , stick the fragments in there and then 
  we only have one file for for plugin which is more beatiful I think. But changing `collectd::plugin`
  has quite some consquences.

**Comment by traylenator** [comment]
The fact that 

```puppet
oncat{'/tmp/file':
  ensure => present,
}
concat::fragment{'a snippet':
  content => 'foo',
  target  => '/tmp/file',
}

file{'/tmp/file':
  ensure => absent,
}
```
is a valid manifest and does not give a compile error is really undesirable.

The above currently purges the file.

**Comment by alexjfisher** [comment]
This is much different to how a `file_line` resource and `file` resource can conflict though?

**Comment by traylenator** [comment]
> This isn't much different to how a file_line resource and file resource can conflict though?

I think you normally at least see puppet apply doing something in this case, you get an oscillation. With the above there is zero change when puppet apply so long as the file is not there.
Not sure anything can be done, its just easy to fall into.

**Comment by paramite** [comment]
I don't understand what is wrong here. IIUC to have the processes-config.conf created you need to use collectd::plugin::processes with appropriate process_matches value, which IIUC you did not use, so it is kind of expected that the config is not created.

**Comment by traylenator** [comment]
> I don't understand what is wrong here. IIUC to have the processes-config.conf created you need to use collectd::plugin::processes with appropriate process_matches value, which IIUC you did not use, so it is kind of expected that the config is not created.

Even with `process_matches` values then `processes-config.conf ` is created as a concat file
but the file resource of absent wins the day.

**Comment by paramite** [comment]
Ah got it. So where does the file resource with absent comes from?

**Comment by traylenator** [comment]
From the commit above: https://github.com/voxpupuli/puppet-collectd/commit/a864d0d58815d58c944277417dcf52df2d3c7572

it was added to stop default files form packages interfering.

**Comment by paramite** [comment]
@traylenator: Ah, now I understand why you pinged me regarding this :). So if we want to have the processes plugin config name consistent with the rest, then yes rename to something like <priority>-processes.conf should be a solution. If we want to keep the name, then probably adding `require => File['package_processes.load']` (in combination with `defined(File['package_processes.load'])`) to the concat and fragments resources should also work, right? I'm not core in this project, so maybe @alexjfisher will show the correct path we should go?

**Comment by traylenator** [comment]
The fix I prefer to this problem of package config vs puppet config is just to avoid the problem and
use say `/etc/collectd-puppet/conf.d` and ignore the contents of `/etc/collectd.d` . Works well but a little non standard.
