### ISSUE TITLE
Upgrade puppet-epel version

### ISSUE THREAD

**Issue by waipeng** [voxpupuli/puppet-collectd#999]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-agent-7.17.0-1.el8.x86_64
- Ruby:
- Distribution: RHEL 8
- Module version: 13.0.0

## Any additional information you'd like to impart

It appears we now need https://github.com/voxpupuli/puppet-epel/pull/130 in v4.0, v4.1 of puppet-epel for RHEL 8 to work.

Given that RHEL 8 is supported by this module, can we bumped up the version in metadata.json?

Would you like me to propose a PR?

**Comment by zilchms** [comment]
bit late for me for this, but fixed in #1004 and been released for some time to forge now. so i will close this :)
